include:
    - project: "vivid/gitlab-ci"
      file: "templates/s2i-template.yml"

stages:
    - lint
    - build

lint:
    stage: lint
    script:
        - INSTALL_DEPS=1 RUN_AS_UID=`id -u` ./lint.sh
    tags:
        - ec2
    only:
        - master
        - merge_requests

#admin-build-and-push:
#    extends: .s2i-build-and-push
#    stage: build
#    variables:
#        BUILD_CONTEXT: "admin"
#        BASE_IMAGE: # TODO: INSERT BASE IMAGE NAME HERE
#        IMAGE_NAME: # TODO: INSERT TARGET IMAGE NAME HERE
